### ISSUE TITLE
In casbin/dbal-adapter, the loadPolicy method runs select the column ptype, but the table is p_type

### ISSUE THREAD

**Issue by 894480109** [php-casbin/dbal-adapter#1]
https://github.com/casbin/casbin/issues/661

The file is src/Adapter.php，on Line 117, Thanks!

**Comment by techoner** [comment]
@894480109  Indeed, the field names are not exactly the same in different languages, but `ptype` is used uniformly in `PHP-Casbin`.

**Comment by hsluoyz** [comment]
@894480109 are you using 2 or more languages? Like Go and PHP?

**Comment by 894480109** [comment]
> @894480109 are you using 2 or more languages? Like Go and PHP?

Yes, you are right, another project is Go, but I use PHP, and I have to read the table to show the rbac or privilege list, now I overload the adapter class to solve the problem, can you give some other advice? Thanks!

**Comment by 894480109** [comment]
> @894480109 Indeed, the field names are not exactly the same in different languages, but `ptype` is used uniformly in `PHP-Casbin`.

Hopefully can use cross the languages with the table structure，Thanks!

**Comment by hsluoyz** [comment]
@techoner I think the Go lib should be treated as standard. The PHP side can be modified to use p_type.

**Comment by techoner** [comment]
@894480109  It has been fixed in version 2.0.
[DBAL adapter 2.0.0](https://github.com/php-casbin/dbal-adapter/releases/tag/v2.0.0)

**Comment by 894480109** [comment]
> @894480109 It has been fixed in version 2.0.
> [DBAL adapter 2.0.0](https://github.com/php-casbin/dbal-adapter/releases/tag/v2.0.0)

Good jobs! Thanks !
